### ISSUE TITLE
ADD TRY-CATCH TO CAMERA APP LOGIC

### ISSUE THREAD

**Issue by tyriem** [tyriem/ION#1]
https://github.com/tyriem/ION/blob/8218bda331f2e7bb1000d2141e6c678401d92973/ION4-IOSPHOTO/src/pages/Home.tsx#L16-L16

**Comment by aaronksaunders** [comment]
see - https://www.notion.so/in3dcpersonal/Day-2-Working-with-Camera-Plugin-a23582008df749a1b3fd496bef9232f8#520a59ed694148c9a4966bafc497b5be

**Comment by tyriem** [comment]
> see - https://www.notion.so/in3dcpersonal/Day-2-Working-with-Camera-Plugin-a23582008df749a1b3fd496bef9232f8#520a59ed694148c9a4966bafc497b5be

Solution outline received with thanks. Flagged for implementation.
