### ISSUE TITLE
STYLING JSON OUTPUT WHEN STRINGIFIED

### ISSUE THREAD

**Issue by tyriem** [tyriem/ION#2]
https://github.com/tyriem/ION/blob/c286336f49a2745733bfcfcdcabcbba791dc707f/ION8-LOGIN/src/components/Menu.tsx#L88

When outputting JSON value with the syntax: `JSON.stringify(supabase.auth.user(), ['email']`
What is the best method to grab just the value and print it appealingly to the user in the style:
`user@email.com` ?

@tyriem
@aaronksaunders
@aaron@clearlyinnovative.com

**Comment by aaronksaunders** [comment]
you don't need to stringify it.
```
<IonNote>
  supabase.auth.user()?.email
</IonNote> 
```

**Comment by tyriem** [comment]
> you don't need to stringify it.
> 
> ```
> <IonNote>
>   supabase.auth.user()?.email
> </IonNote> 
> ```

Duly noted, is there any notable benefit to stringifying it over not?

**Comment by aaronksaunders** [comment]
stringify is just extra work, not needed

**Comment by tyriem** [comment]
> stringify is just extra work, not needed

Noted and implemented as suggested, stringify left in place but deprecated. Thank you for your solution suggestion.
